### PR TITLE
More units for length and energy

### PR DESCRIPTION
**Pull request by Luthaf**
Add more known units for length and energy, including most of the (non-combined) units from https://docs.lammps.org/units.html

# Contributor (creator of pull-request) checklist

 - [ ] ~Tests updated (for new features and bugfixes)?~
 - [x] Documentation updated (for new features)?
 - [ ] ~Issue referenced (for PRs that solve an issue)?~

# Reviewer checklist

 - [ ] CHANGELOG updated with public API or any other important changes?

----
📚 Documentation preview 📚: https://metatensor--570.org.readthedocs.build/en/570/

### CODE REVIEW

**Comment by frostedoyster** [comment]
A random question: why Hartree and not Ha?
I just tried to train on QM9 and "Ha" didn't work

**Comment by Luthaf** [comment]
No real reason! I'm trying to limit how many variations of the same unit we have. Right now `nm` and `nanometer` is the only duplicated unit, I could even remove that. 

From a user point of view, trying Ha and getting an error telling to use Hartree should not be too bad, right?

**Comment by Luthaf** [comment]
Actually, I changed my mind. It will be more useful (in particular for integration with MD engines) to support a larger set of units (for example plumed uses `nm`, `A`, `Bohr`). So I've added a bunch of alternative unit spelling, and we can add more to it later.

**Comment by Luthaf** [comment]
> A random question: why Hartree and not Ha?

Is `Ha` an abbreviation used anywhere? I could not find it online.

**Comment by frostedoyster** [comment]
You're right. It seems to be E_h everywhere

**Review by frostedoyster — APPROVED** [review]

**Pull request merged**
