### PR TITLE
Release metatensor-learn v0.1.0 and metatensor-python v0.2.0

### PR DESCRIPTION
**Pull request by Luthaf**
metatensor-python v0.2.0 adds a dependency on metatensor-learn, and remove version constrains for the metatensor-xxx packages, allowing to automatically pick up new releases.

----
📚 Documentation preview 📚: https://metatensor--457.org.readthedocs.build/en/457/

### CODE REVIEW

**Comment by Luthaf** [comment]
We might want to wait for #427 to be merged before merging this one!

**Comment by agoscinski** [comment]
Give me 3 more hours, I will go through the PR now

**Comment by Luthaf** [comment]
No worries, I'm not in a hurry.

**Review by agoscinski — APPROVED** [review]
Clear to me

**Pull request merged**
