### PR TITLE
Add ModelCapabilities::dtype, picked by the model

### PR DESCRIPTION
**Pull request by Luthaf**
The dtype is picked by the model, and the engine has to convert data on input/output to whatever it needs (similar to how different devices are handled).

# Contributor (creator of pull-request) checklist

 - [x] Tests updated (for new features and bugfixes)?
 - [x] Documentation updated (for new features)?
 - [ ] ~Issue referenced (for PRs that solve an issue)?~

# Reviewer checklist

 - [ ] CHANGELOG updated with public API or any other important changes?

----
📚 Documentation preview 📚: https://metatensor--551.org.readthedocs.build/en/551/

### CODE REVIEW

**Comment by Luthaf** [comment]
> I thought he plan was the model basically has to accept the dtype the model gets from the engine and try work with it as best as it can?

Err, I understood it the other way around ^_^. The model decide what it wants, and the engine must adapt around it (like for device).

This might be a bit different for metatensor-models, where the "engine" is also the one creating the model. But at this point capabilities don't exist yet.

**Comment by PicoCentauri** [comment]
> > I thought he plan was the model basically has to accept the dtype the model gets from the engine and try work with it as best as it can?
> 
> Err, I understood it the other way around ^_^. The model decide what it wants, and the engine must adapt around it (like for device).

Okay, I really thought the other way around based on the discussion on slack

Screenshot 2024-03-18 at 16 38 08

But, I see that this might be hard for a model that use hardcoded `dtypes` like PET. So we can use the `dtype` as `capabilities `

> This might be a bit different for metatensor-models, where the "engine" is also the one creating the model. But at this point capabilities don't exist yet.

Yes, there the user picks the `dtype` and in the end we would inject this into the new `capabilities` that you have implemented.

**Comment by Luthaf** [comment]
There was some misunderstanding with Marcel, because it seems that in jax models can do automatic casting if the weights don't match the inputs. Torch can not do that, hence why it makes sense to pick dtype once and stay with it.

**Review by PicoCentauri — APPROVED** [review]
Okay, I get it now! LGTM then.

**Pull request merged**
