### PR TITLE
Feature/sort by

### PR DESCRIPTION
**Pull request by DavideTisi**
I added the possibility to sort only by some columns in a specific axis, using `name`

----
 📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1570536484.zip)

### CODE REVIEW

**Comment by DavideTisi** [comment]
I open the pr to trigger the CI

**Comment by DavideTisi** [comment]
I am opening this PR to understand what we want to do. 
This PR has two parts (and it fails in both):
- one try to fix #642, @jwa7 example (that I added to the tests) now works, but the torch algo is not a real solution there are other case in which it fails
- two the main reason I started this pr. I wanted a "sort by name" function basically instead of sorting everything it sorts following the column with `name=name`

**Comment by Luthaf** [comment]
I think this can be rebased to only contain the `sort_by` functionality now that #647 is merged.

**Comment by DavideTisi** [comment]
Yes sure

**Comment by Luthaf** [comment]
Closing for now, will be re-opened when ready!

**Pull request closed without merging**
